{% set version = "4.36" %}

package:
  name: sesimcmc
  version: {{ version }}

source:
  git_rev: v4.36
  git_url: https://github.com/favorov/SeSiMCMC.git

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
